services:
  web:
    container_name: segurosunimeddesafio
    build:
      context: .
      dockerfile: Dockerfile
    image: segurosunimeddesafio
    ports:
      - "8080:8080"
    restart: unless-stopped